#!/usr/bin/env ruby
# frozen_string_literal: true

require 'sneakers'
require 'logger'
require 'sneakers/runner'

# Worker
class Processor
  include Sneakers::Worker
  from_queue '11.sneakers'

  def work(msg)
    puts msg

    ack!
  end
end

# Configuration
Sneakers.configure  daemonize:  false,
                    log:        STDOUT,
                    workers:    ENV.fetch('WORKERS', 2).to_i,
                    threads:    ENV.fetch('THREADS', 3).to_i,
                    prefetch:   ENV.fetch('PREFETCH', 3).to_i,
                    heartbeat:  ENV.fetch('HEARTBEAT', 60).to_i

Sneakers.logger.level = Logger::INFO

# Runner
runner = Sneakers::Runner.new([Processor])
runner.run
