#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bunny'

connection = Bunny.new
connection.start

channel = connection.create_channel
exchange = channel.default_exchange

routing_keys = [
  '02.queue1',
  '02.queue2'
]

puts 'Type your messages'

begin
  loop do
    message = readline.chomp

    routing_key = routing_keys.sample

    exchange.publish(message, routing_key: routing_key)
  end
rescue Interrupt => _
  channel.close
  connection.close
end
