#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bunny'

connection = Bunny.new
connection.start

channel = connection.create_channel

queue = channel.queue('06.priorities', arguments: { 'x-max-priority' => 100 })

begin
  queue.subscribe(block: true) do |_delivery_info, _properties, msg|
    putc msg
  end
rescue Interrupt => _
  channel.close
  connection.close
end
