# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f5acbed93b5ff47e810e8b3c9826b5479beb8d6526c0c10779efef397b4321cde7ff605120b1e2929059fd38514c5d20a9d612c125dcc08f8034ca6a43c8d0e

test:
  secret_key_base: 6a99d88a5e7a1bd7efd7f5ccc3af4defb1cd676da6bc1387f8e60e4355b3222d33939f5babe8483e75010f7eff54b5ce6179b3eff5a26d8c310d0edd1fbefdec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
